# Generated by Django 5.1.7 on 2026-03-30 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Template",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "module",
                    models.CharField(
                        choices=[
                            ("form1", "Форма 1 — Персонал"),
                            ("form2", "Форма 2 — СИ"),
                            ("form3", "Форма 3 — ИО"),
                            ("form4", "Форма 4 — Вспом. оборудование"),
                            ("form5", "Форма 5 — СО"),
                        ],
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="TemplateVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                ("file", models.FileField(upload_to="template_versions/%Y/%m/%d")),
                (
                    "file_format",
                    models.CharField(
                        choices=[("docx", "DOCX"), ("xlsx", "XLSX")], max_length=10
                    ),
                ),
                ("placeholder_schema", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="templates_engine.template",
                    ),
                ),
            ],
            options={
                "unique_together": {("template", "version")},
            },
        ),
        migrations.CreateModel(
            name="GeneratedDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entity_type", models.CharField(max_length=32)),
                ("entity_id", models.PositiveIntegerField()),
                ("generated_file", models.FileField(upload_to="generated/%Y/%m/%d")),
                ("generated_by", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "template_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="templates_engine.templateversion",
                    ),
                ),
            ],
        ),
    ]
